name: Dev build and push image to ghci repo

on:
  push:
    branches: [ main, auth-drive ]
    paths:
      - 'Cargo.toml'
      - 'Dockerfile.local'
      - 'oauth/src'
      - 'config/default.toml'
      - 'config/development.toml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        default: 'dummy input'
        required: true
      tags:
        description: 'dummy input, ignore'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Github registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
         name: create unique tag
         run: |
           echo "IMAGE_ID=ghcr.io/lucivia/auth-img-dev:$GITHUB_RUN_ID" >> $GITHUB_ENV
      -
        name: Build and push images as latest
        uses: docker/build-push-action@v2.9.0
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile.local
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/lucivia/auth-img-dev:latest, ${{ env.IMAGE_ID }}

        # run: |
        #    IMAGE_ID=ghcr.io/lucivia/auth-img:$GITHUB_RUN_ID
        #    docker buildx build . -f Dockerfile.scratch -t $IMAGE_ID
        #    docker push $IMAGE_ID

        # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
