name: Build and push docker image with buildx

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile.scratch'
      - 'oauth/src'
      - 'config/default.toml'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Do not change'
        required: true
        default: 'dummy input'
      tags:
        description: 'dummy input, ignore'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to Github registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      -
        name: Create the image id
        run: |
           echo "IMAGE_ID=ghcr.io/lucivia/auth-img:$GITHUB_RUN_ID" >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile.scratch
          tags: ${{ env.IMAGE_ID }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

 #     - name: Build image
 #       run: |
 #         IMAGE_ID=ghcr.io/lucivia/auth-img:$GITHUB_RUN_ID
 #         DOCKER_BUILDKIT=1 docker build . -t $IMAGE_ID -f Dockerfile.scratch
 #         docker push $IMAGE_ID
